### ISSUE TITLE
I appreciate you!

### ISSUE THREAD

**Issue by FridayCandour** [webmaxru/push.foo#1]
Thank you for this pwa notification demonstration and am very happy you provided your sources which is a great inspiration for me too.

**Comment by webmaxru** [comment]
Thank you for your kind words!

**Comment by FridayCandour** [comment]
Please create a discussion on the repo, well I don't know how that works but couldn't find it.

**Comment by webmaxru** [comment]
Here we go!
https://github.com/webmaxru/push.foo/discussions/2
